export const ASSETS = {
  uiFont: { key: "ui.font.future", path: "./assets/kenney/ui-pack-sci-fi/kenney-future.ttf", type: "font" },
  games: {
    space: [
      ["bg", "./assets/kenney/space-shooter-remastered/bg-dark-purple.png", "image"],
      ["player", "./assets/kenney/space-shooter-remastered/player-ship-blue.png", "image"],
      ["enemyBlack", "./assets/kenney/space-shooter-remastered/enemy-black-1.png", "image"],
      ["enemyRed", "./assets/kenney/space-shooter-remastered/enemy-red-3.png", "image"],
      ["meteorBrown", "./assets/kenney/space-shooter-remastered/meteor-brown-big-1.png", "image"],
      ["meteorGrey", "./assets/kenney/space-shooter-remastered/meteor-grey-big-2.png", "image"],
      ["laser", "./assets/kenney/space-shooter-remastered/laser-blue-01.png", "image"],
      ["bolt", "./assets/kenney/space-shooter-remastered/power-bolt.png", "image"],
      ["shield", "./assets/kenney/space-shooter-remastered/power-shield.png", "image"],
      ["star", "./assets/kenney/space-shooter-remastered/star-gold.png", "image"],
      ["laserSfx", "./assets/kenney/space-shooter-remastered/sfx-laser.ogg", "audio"],
      ["scoreSfx", "./assets/kenney/space-shooter-remastered/sfx-score.ogg", "audio"],
      ["loseSfx", "./assets/kenney/space-shooter-remastered/sfx-lose.ogg", "audio"],
    ],
    platformer: [
      ["playerStand", "./assets/kenney/platformer-art-deluxe/player-stand.png", "image"],
      ["playerJump", "./assets/kenney/platformer-art-deluxe/player-jump.png", "image"],
      ["playerWalk1", "./assets/kenney/platformer-art-deluxe/player-walk-01.png", "image"],
      ["playerWalk2", "./assets/kenney/platformer-art-deluxe/player-walk-05.png", "image"],
      ["playerWalk3", "./assets/kenney/platformer-art-deluxe/player-walk-09.png", "image"],
      ["grassMid", "./assets/kenney/platformer-art-deluxe/tile-grass-mid.png", "image"],
      ["grassCenter", "./assets/kenney/platformer-art-deluxe/tile-grass-center.png", "image"],
      ["grassLeft", "./assets/kenney/platformer-art-deluxe/tile-grass-left.png", "image"],
      ["grassRight", "./assets/kenney/platformer-art-deluxe/tile-grass-right.png", "image"],
      ["dirt", "./assets/kenney/platformer-art-deluxe/tile-dirt-mid.png", "image"],
      ["coin", "./assets/kenney/platformer-art-deluxe/coin-gold.png", "image"],
      ["gemBlue", "./assets/kenney/platformer-art-deluxe/gem-blue.png", "image"],
      ["gemGreen", "./assets/kenney/platformer-art-deluxe/gem-green.png", "image"],
      ["flag", "./assets/kenney/platformer-art-deluxe/flag-yellow.png", "image"],
      ["spikes", "./assets/kenney/platformer-art-deluxe/spikes.png", "image"],
      ["cloud", "./assets/kenney/platformer-art-deluxe/cloud-1.png", "image"],
      ["slime", "./assets/kenney/platformer-art-deluxe/slime.png", "image"],
      ["slimeWalk", "./assets/kenney/platformer-art-deluxe/slime-walk.png", "image"],
    ],
    tank: [
      ["player", "./assets/kenney/top-down-tanks-remastered/tank-blue.png", "image"],
      ["enemyRed", "./assets/kenney/top-down-tanks-remastered/tank-red.png", "image"],
      ["enemyGreen", "./assets/kenney/top-down-tanks-remastered/tank-green.png", "image"],
      ["enemyDark", "./assets/kenney/top-down-tanks-remastered/tank-dark.png", "image"],
      ["bulletBlue", "./assets/kenney/top-down-tanks-remastered/bullet-blue.png", "image"],
      ["bulletRed", "./assets/kenney/top-down-tanks-remastered/bullet-red.png", "image"],
      ["grass", "./assets/kenney/top-down-tanks-remastered/tile-grass-1.png", "image"],
      ["crate", "./assets/kenney/top-down-tanks-remastered/crate-wood.png", "image"],
      ["barrel", "./assets/kenney/top-down-tanks-remastered/barrel-red-top.png", "image"],
      ["sandbag", "./assets/kenney/top-down-tanks-remastered/sandbag-beige.png", "image"],
      ["explosion", "./assets/kenney/top-down-tanks-remastered/explosion-1.png", "image"],
    ],
    racer: [
      ["car", "./assets/kenney/racing-pack/car-red-1.png", "image"],
      ["ghostCar", "./assets/kenney/racing-pack/car-blue-1.png", "image"],
      ["road", "./assets/kenney/racing-pack/road-asphalt-22.png", "image"],
      ["corner", "./assets/kenney/racing-pack/road-asphalt-01.png", "image"],
      ["cone", "./assets/kenney/racing-pack/cone-straight.png", "image"],
      ["oil", "./assets/kenney/racing-pack/oil.png", "image"],
      ["barrier", "./assets/kenney/racing-pack/barrier-red.png", "image"],
      ["tree", "./assets/kenney/racing-pack/tree-small.png", "image"],
    ],
    match3: [
      ["back", "./assets/kenney/puzzle-pack-2/back-tile-05.png", "image"],
      ["blue", "./assets/kenney/puzzle-pack-2/tile-blue-01.png", "image"],
      ["green", "./assets/kenney/puzzle-pack-2/tile-green-01.png", "image"],
      ["red", "./assets/kenney/puzzle-pack-2/tile-red-01.png", "image"],
      ["yellow", "./assets/kenney/puzzle-pack-2/tile-yellow-01.png", "image"],
      ["orange", "./assets/kenney/puzzle-pack-2/tile-orange-01.png", "image"],
      ["pink", "./assets/kenney/puzzle-pack-2/tile-pink-01.png", "image"],
      ["coin", "./assets/kenney/puzzle-pack-2/coin-01.png", "image"],
    ],
    memory: [
      ["back", "./assets/kenney/playing-cards-pack/card-back.png", "image"],
      ["heartsA", "./assets/kenney/playing-cards-pack/card-hearts-a.png", "image"],
      ["heartsK", "./assets/kenney/playing-cards-pack/card-hearts-k.png", "image"],
      ["diamondsQ", "./assets/kenney/playing-cards-pack/card-diamonds-q.png", "image"],
      ["diamonds10", "./assets/kenney/playing-cards-pack/card-diamonds-10.png", "image"],
      ["spadesK", "./assets/kenney/playing-cards-pack/card-spades-k.png", "image"],
      ["spades7", "./assets/kenney/playing-cards-pack/card-spades-07.png", "image"],
      ["clubs2", "./assets/kenney/playing-cards-pack/card-clubs-02.png", "image"],
      ["clubsJ", "./assets/kenney/playing-cards-pack/card-clubs-j.png", "image"],
      ["jokerRed", "./assets/kenney/playing-cards-pack/card-joker-red.png", "image"],
      ["jokerBlack", "./assets/kenney/playing-cards-pack/card-joker-black.png", "image"],
    ],
  },
};

export function getGameAssets(gameId) {
  return (ASSETS.games[gameId] || []).map(([name, path, type]) => ({ name, path, type }));
}
